import { Container, Title, Text, Space } from "@mantine/core";
import { createFileRoute } from "@tanstack/react-router";
import StakingService from "../../services/StakingService";
import StakingStats from "../../components/Staking/StakingStats/StakingStats";
import StakingAccount from "../../components/Staking/StakingAccount/StakingAccount";

function Index() {
  return (
    <Container
      size="md"
      my="md"
      px={{
        xs: "md",
        sm: "xl",
      }}
    >
      <Title order={2}>$GFM staking</Title>
      <Text lh={1.2} mb="xs" c="dimmed">
        Earn your share of all fees generated by the GoFundMeme protocol
      </Text>
      <StakingService>
        <StakingStats />
        <Space h="md" />
        <StakingAccount />
      </StakingService>
    </Container>
  );
}

export const Route = createFileRoute("/_layout/")({
  component: Index,
});
